# Generated by Django 4.0.2 on 2022-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoddySection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dates', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(max_length=100)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoddySection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pragraph', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dates', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(max_length=100)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoddySection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pragraph', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dates', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(max_length=100)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BoddySection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('pragraph', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dates', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph1', models.TextField(blank=True, null=True)),
                ('paragraph2', models.TextField(blank=True, null=True)),
                ('heading1', models.CharField(max_length=100)),
                ('paragraph3', models.TextField(blank=True, null=True)),
                ('heading2', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph4', models.TextField(blank=True, null=True)),
                ('heading3', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph5', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(blank=True, max_length=20, null=True)),
                ('inst_link', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=100, null=True)),
                ('ind_link', models.CharField(blank=True, max_length=100, null=True)),
                ('com_footer', models.CharField(blank=True, max_length=100, null=True)),
                ('comDate_footer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
